In [1]:
import yfinance as yf

datos_h1 = yf.download("GC=F", period="730d", interval="1h")
datos_h1.head()

[*********************100%***********************]  1 of 1 completed

Price,Close,High,Low,Open,Volume
Ticker,GC=F,GC=F,GC=F,GC=F,GC=F
Datetime,,,,,
2024-03-20 00:00:00-04:00,2159.800049,2163.300049,2159.800049,2163.000000,0
2024-03-20 01:00:00-04:00,2160.399902,2161.199951,2159.500000,2159.899902,1582
2024-03-20 02:00:00-04:00,2159.800049,2161.100098,2159.199951,2160.300049,3279
2024-03-20 03:00:00-04:00,2161.000000,2162.399902,2159.699951,2159.899902,3805
2024-03-20 04:00:00-04:00,2158.899902,2161.199951,2157.300049,2160.899902,6001

In [2]:
datos_h1.columns = datos_h1.columns.get_level_values(0)
datos_h1.columns.name = None
datos_h1 = datos_h1[["Open", "High", "Low", "Close", "Volume"]]

datos_h1.head()

,Open,High,Low,Close,Volume
Datetime,,,,,
2024-03-20 00:00:00-04:00,2163.000000,2163.300049,2159.800049,2159.800049,0
2024-03-20 01:00:00-04:00,2159.899902,2161.199951,2159.500000,2160.399902,1582
2024-03-20 02:00:00-04:00,2160.300049,2161.100098,2159.199951,2159.800049,3279
2024-03-20 03:00:00-04:00,2159.899902,2162.399902,2159.699951,2161.000000,3805
2024-03-20 04:00:00-04:00,2160.899902,2161.199951,2157.300049,2158.899902,6001

In [3]:
datos_h1.to_csv("../data/XAUUSD_h1.csv")
print("Datos H1 guardados correctamente")

Datos H1 guardados correctamente